# .nosana-ci.yml
global:
  image: node:16
  trigger:
    push:
      branches:
        - main
      tags:
        - 'v*'
    pull_request:
      branches:
        - test

jobs:
  - name: build
    commands:
      - npm ci
    artifacts:
      - name: node_modules

  - name: test
    commands:
      - echo "testing..."
      - npx hardhat install
    resources:
      - name: node_modules
