# .nosana-ci.yml
nosana:
  description: Build, Test and Deploy software

global:
  image: node:19
  trigger:
    push:
      branches:
        - main

jobs:
  - name: build
    commands:
      - npm ci
      - npx hardhat compile