# .nosana-ci.yml
nosana:
  description: Build, Test and Deploy software.

global:
  image: node:16
  trigger:
    push:
      branches:
        - main

jobs:
  - name: build
    commands:
      - npm ci
      - npx hardhat compile
      - sleep 300
  - name: test
    trigger:
      push:
        branches:
          - dev
    environment:
      REPORT_GAS: "true"
    commands:
      - npx hardhat test
    resources:
      - name: node_modules
      - name: artifacts
