# .nosana-ci.yml
global:
  image: node:16
  trigger:
    push:
      branches:
        - main

jobs:
  - name: build
    commands:
      - npm ci
      - npx hardhat compile
  - name: step2
    commands:
      - echo 'step2'
      - sleep 10
  - name: step3
    commands:
      - echo 'step2'
      - sleep 10
  - name: test
    trigger:
      push:
        branches:
          - dev
    environment:
      REPORT_GAS: "true"
    commands:
      - npx hardhat test
    resources:
      - name: node_modules
      - name: artifacts
