# .nosana-ci.yml
global:
  image: node:16
  trigger:
    push:
      branches:
        - main
      tags:
        - 'v*'

jobs:
  - name: build-devnet
    commands:
      - npm ci
      - npx hardhat compile
    trigger:
      push:
        branches:
          - main
  - name: build-mainnet
    commands:
      - echo 'only run on tag creation'
    trigger:
      push:
        tags:
         - 'v*'
  - name: build-everything
    commands:
      - echo 'run on everything'
